# Generated by Django 3.0 on 2021-04-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usrg',
            old_name='age',
            new_name='ag',
        ),
    ]
